version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd auth/
  build:
    commands:
      - echo Build started on `date`
      - npm install /auth/**/
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - scripts/
    - auth/
    - index.js
    - node_modules/**/*