version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
      - location: scripts/build.sh
        timeout: 300
        runas: ubuntu
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - scripts/
    - auth/
    - index.js
    - node_modules/**/*