version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo installing
  build:
    commands:
      - echo Build started on `date`
      - npm install --global lerna 
      - lerna bootstrap --concurrency=1 -- --production
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - scripts/
    - auth/
    - index.js
    - node_modules/**/*